---
:development:
  :host: '127.0.0.1'
  :port: 2379
  :user_name: ''
  :password: ''

:test:
  :host: '127.0.0.1'
  :port: 2379
  :user_name: ''
  :password: ''

:production:
  :host: '127.0.0.1'
  :port: 2379
  :user_name: ''
  :password: ''


